name: On Commit Workflow

on:
  push:
    branches:
      - assignment-02

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Hello World
      run: echo "Hello World"
